---
name: Test and Build
on: workflow_dispatch
#  pull_request:
#    branches:
#    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.16.3
    steps:
      - run: |
          ls
